
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkrhdzchnubbzsbgvmze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcmhkemNobnViYnpzYmd2bXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzY3MjMsImV4cCI6MjA1NzcxMjcyM30._UfLT9qOwOqTPL4oq29lnJuIp1UcHB6RhG_VsJh5zIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
